### ISSUE TITLE
New maintainer for Lavender

### ISSUE THREAD

**Issue by UsiFX** [elytraOS/vendor_elytra#1]
## Device you want to apply for

Xiaomi Redmi Note 7 (Lavender)

## Device tree sources

[Device Tree](https://github.com/UsiFX/device_xiaomi_lavender)
[Device Tree Common](https://github.com/UsiFX/device_xiaomi_sdm660-common)
[Kernel Tree](https://github.com/UsiFX/kernel_xiaomi_lavender)
[Vendor Tree](https://github.com/UsiFX/vendor_xiaomi_lavender)
[Vendor Tree Common](https://github.com/UsiFX/vendor_xiaomi_sdm660-common)
[Extras Repo](https://github.com/UsiFX/device_xiaomi_extras)

## Link to the platform where you have released your unofficial build

[Telegram Post](https://t.me/xprjkts/340)

## Other ROM's you maintain officially or unofficially

None

## Bugs on unofficial build

None

## How long have you been building for?

3 months (Since last November)

## SELinux status?

Enforcing.

## Are you using a prebuilt kernel? If yes, why?

No.

### Telegram username

[@ImUsiF12](https://t.me/ImUsiF12)

**Comment by Rasenkai** [comment]
Accepted, do a pull req and add your device to elytra.devices.
